name: GoCache

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17


  build:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: go build -v ./...
      - name: Cache files
        uses: actions/cache@v2
        with:
          path: *
          key: ${{ runner.os }}-go

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/cache@v2
        id: cache
        with:
          path: *
          key: ${{ runner.os }}-go
      - name: Test
        run: go test -v ./...